#!/bin/bash

# Usage:
#   ./clean_all.sh 
# This script cleans up all the output and log files generated by the simulation runs.

# Confirm before deletion
read -p "Are you sure you want to delete the outputs and logs? (y/n): " confirm
if [[ "$confirm" != "y" ]]; then
    echo "Aborting clean-up."
    exit 1
fi

# delete output folder if it exists
if [ -d "./outputs" ]; then
    rm -rf ./outputs
    echo "[INFO] Outputs directory deleted."
else
    echo "[INFO] Outputs directory not found."
fi

# delete log folder if it exists
if [ -d "./logs" ]; then
    rm -rf ./logs
    echo "[INFO] Logs directory deleted."
else
    echo "[INFO] Logs directory not found."
fi

# End of script
